name: Developer_Branch_CI
on:
  push:
    branches:
      - 'XPNS-*'
env:
  service_name: expense-frontend

jobs:
  CI_Steps:
    uses: teju-devopss/github-actions/.github/workflows/Developer_Branch_CI.yml@main
    secrets: inherit
    with:
      service_name: expense-frontend