name: Developer_Pull_Request_CI
on:
  pull_request:
    branches:
      - 'main'

env:
  service_name: expense-frontend

jobs:
  CI_Steps:
    uses: teju-devopss/github-actions/.github/workflows/Developer_Pull_Request_CI.yml@main