name: Release_Tags
on:
  push:
    tags:
      - 'v*'
env:
  service_name: expense-frontend

jobs:
  CI_Steps:
    uses: teju-devopss/github-actions/.github/workflows/Release_Tags.yml@main
    secrets: inherit
    with:
     service_name: expense-frontend